name: Build & Deploy

on: [push]

env:
  NODE_VERSION: '17.x'
  PHP_VERSION: '8.0'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repository
        uses: actions/checkout@v2

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --working-dir backend --no-dev --prefer-dist --no-progress --no-suggest

      - name: Setup Node ${{ env.NODE_VERSION }} and NPM
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install NPM dependencies
        run: npm --prefix frontend ci

      - name: Build JS application
        run: npm --prefix frontend run build

      - name: Setup database
        run: |
          composer install --working-dir database --prefer-dist --no-progress --no-suggest
          composer db:setup --working-dir database
          mv database backend/database

      - name: Deploy to server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "backend"
          target: ${{ secrets.SSH_TARGET }}
          strip_components: 1
